service:
  name: urlShrtnrApi

plugins:
  - serverless-step-functions
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'eu-west-1'}
  memorySize: 512
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:PutItem"
      Resource: !GetAtt UrlsTable.Arn
    - Effect: "Allow"
      Action:
        - "states:StartExecution"
      Resource:
        Ref: SaveUrlStateMachine
    - Effect: "Allow"
      Action:
        - "states:DescribeExecution"
      Resource: arn:aws:states:#{AWS::Region}:#{AWS::AccountId}:execution:saveUrl-${self:provider.stage}:*

functions:
  shortenUrl:
    handler: management-api.shortenUrl
    environment:
      SAVE_URL:
        Ref: SaveUrlStateMachine
    events:
      - http: POST shorten
  retryGuard:
    handler: save-urls.retryGuard
    name: ${self:service}-retryGuard-${self:provider.stage}
  generateId:
    handler: save-urls.generateId
    name: ${self:service}-generateId-${self:provider.stage}
  saveUrl:
    handler: save-urls.saveUrl
    name: ${self:service}-saveUrl-${self:provider.stage}
    environment:
      TABLE_NAME:
        Ref: UrlsTable

stepFunctions:
  stateMachines:
    saveUrl:
      name: saveUrl-${self:provider.stage}
      id: SaveUrlStateMachine
      definition:
        Comment: Generate a short id for a URL and respond synchronously
        StartAt: RetryGuard
        States:
          RetryGuard:
            Type: Task
            Resource: arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:${self:service}-retryGuard-${opt:stage}
            Next: RetryCheck
          RetryCheck:
            Type: Choice
            Choices:
              - Variable: $.retries
                NumericGreaterThan: 3
                Next: RetriesExceeded
            Default: GenerateId
          RetriesExceeded:
            Type: Fail
            Cause: Retries Exceeded
          GenerateId:
            Type: Task
            Resource: arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:${self:service}-generateId-${opt:stage}
            Next: SaveUrl
          SaveUrl:
            Type: Task
            Resource: arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:${self:service}-saveUrl-${opt:stage}
            End: true
            Catch:
              - ErrorEquals:
                  - ConditionalCheckFailedException
                ResultPath: "$.error-info"
                Next: RetryGuard

resources:
  Resources:
    UrlsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: shortId
            AttributeType: S
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: shortId
            KeyType: HASH