version: 2.1

workflows:
  version: 2
  "Build and deploy":
    jobs:
      - build
      - deploy_dev:
          requires:
            - build
          context: AWS
      - deploy_prod:
          requires:
            - deploy_dev
          context: AWS
jobs:
  build:
    docker:
      - image: circleci/node:10.15

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}

      # run tests!
      - run: npm test

      - store_test_results:
          path: test-results

  deploy_dev:
    docker:
      - image: circleci/node:10.15

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}

      - deploy:
          command: npx serverless deploy --stage dev

  deploy_prod:
    docker:
      - image: circleci/node:10.15

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}

      - deploy:
          command: npx serverless deploy --stage prod