version: 2.1

orbs:
  queue: eddiewebb/queue@1.1.4

workflows:
  version: 2
  "Build and deploy":
    jobs:
      - build
      - deploy_dev:
          requires:
            - build
          context: AWS
      - int_test:
          requires:
            - deploy_dev
      - deploy_prod:
          requires:
            - deploy_dev
          context: AWS
          filters:
            branches:
              only: master
jobs:
  build:
    docker:
      - image: circleci/node:10.15

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm ci

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}

      # run tests!
      - run: npm test

      - store_test_results:
          path: test-results

  int_test:
    docker:
      - image: circleci/node:10.15-browsers

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}

      - run:
          command: |
            mkdir -p test-results
            npx cucumber-js --world-parameters '{"baseUrl":"https://example.com", "shortenerUrl":"'${DEV_SHORTENER_URL}'"}' --format json:test-results/tests.cucumber

      - store_test_results:
          path: test-results

  deploy_int:
    docker:
      - image: circleci/node:10.15

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}

      - deploy:
          command: npx serverless deploy --stage ${CIRCLE_SHA1:0:7}

  deploy_dev:
    docker:
      - image: circleci/node:10.15

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}

      - queue/until_front_of_line:
          consider-branch: false
          time: '10'

      - deploy:
          command: npx serverless deploy --stage dev

  deploy_prod:
    docker:
      - image: circleci/node:10.15

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}

      - queue/until_front_of_line:
          consider-branch: false
          time: '10'

      - deploy:
          command: npx serverless deploy --stage prod